spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.92.217.51:3306/mybatis?characterEncoding=utf8&useSSL=false&serverTimezone=GMT&rewriteBatchedStatements=true
    username: root
    password: Cj969788.+#

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mybatis-plus的全局配置
  global-config:
    db-config:
      # 配置全局的驼峰命名
      db-column-underline: true
      # 配置全局的表名的前缀
      table-prefix: tbl_
      # 配置全局的id策略
      id-type: auto
